// =============================================================
//  WORLD CUP 2026 — FAMILY TIPPING COMP DATA FILE
//  Edit this file to: add tips, update results, add new rounds
//
//  RESULTS: use "home" | "away" | "draw" | null (null = not played)
//  TIPS:    use "home" | "away" | "draw" | null (null = not picked yet)
// =============================================================

const DATA = {

  participants: [
    "Max", "Mackenzie", "Annette", "Stefan", "Xavier",
    "Tony", "Grosi", "Debbie", "Richard", "Olivia", "Sam"
  ],

  // ── GROUP STAGE ───────────────────────────────────────────────
  matches: [

    // ── GROUP A ──────────────────────────────────────────────────
    { id: "A1", stage: "group", group: "A", matchday: 1, date: "2026-06-11", home: "Mexico",       away: "South Africa", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: "home", Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "A2", stage: "group", group: "A", matchday: 1, date: "2026-06-11", home: "South Korea",  away: "Czechia",      result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: "draw", Grosi: "draw", Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "A3", stage: "group", group: "A", matchday: 2, date: "2026-06-18", home: "Czechia",      away: "South Africa", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "A4", stage: "group", group: "A", matchday: 2, date: "2026-06-18", home: "Mexico",       away: "South Korea",  result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "A5", stage: "group", group: "A", matchday: 3, date: "2026-06-24", home: "Czechia",      away: "Mexico",       result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "A6", stage: "group", group: "A", matchday: 3, date: "2026-06-24", home: "South Africa", away: "South Korea",  result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },

    // ── GROUP B ──────────────────────────────────────────────────
    { id: "B1", stage: "group", group: "B", matchday: 1, date: "2026-06-12", home: "Canada",  away: "Bosnia & Herzegovina", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: "home", Grosi: "home", Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "B2", stage: "group", group: "B", matchday: 1, date: "2026-06-12", home: "Qatar",   away: "Switzerland",          result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: "away", Grosi: "away", Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "B3", stage: "group", group: "B", matchday: 2, date: "2026-06-18", home: "Switzerland", away: "Bosnia & Herzegovina", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "B4", stage: "group", group: "B", matchday: 2, date: "2026-06-18", home: "Canada",  away: "Qatar",                result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "B5", stage: "group", group: "B", matchday: 3, date: "2026-06-24", home: "Switzerland", away: "Canada",            result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "B6", stage: "group", group: "B", matchday: 3, date: "2026-06-24", home: "Bosnia & Herzegovina", away: "Qatar",   result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },

    // ── GROUP C ──────────────────────────────────────────────────
    { id: "C1", stage: "group", group: "C", matchday: 1, date: "2026-06-13", home: "Brazil",  away: "Morocco",  result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: "draw", Grosi: "draw", Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "C2", stage: "group", group: "C", matchday: 1, date: "2026-06-13", home: "Haiti",   away: "Scotland", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: "away", Grosi: "away", Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "C3", stage: "group", group: "C", matchday: 2, date: "2026-06-19", home: "Scotland", away: "Morocco", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "C4", stage: "group", group: "C", matchday: 2, date: "2026-06-19", home: "Brazil",  away: "Haiti",    result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "C5", stage: "group", group: "C", matchday: 3, date: "2026-06-24", home: "Scotland", away: "Brazil",  result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "C6", stage: "group", group: "C", matchday: 3, date: "2026-06-24", home: "Morocco", away: "Haiti",    result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },

    // ── GROUP D ──────────────────────────────────────────────────
    { id: "D1", stage: "group", group: "D", matchday: 1, date: "2026-06-12", home: "USA",       away: "Paraguay",  result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: "home", Grosi: "home", Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "D2", stage: "group", group: "D", matchday: 1, date: "2026-06-13", home: "Australia", away: "Türkiye",   result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: "draw", Grosi: "draw", Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "D3", stage: "group", group: "D", matchday: 2, date: "2026-06-19", home: "USA",       away: "Australia", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "D4", stage: "group", group: "D", matchday: 2, date: "2026-06-19", home: "Türkiye",   away: "Paraguay",  result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "D5", stage: "group", group: "D", matchday: 3, date: "2026-06-25", home: "Türkiye",   away: "USA",       result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "D6", stage: "group", group: "D", matchday: 3, date: "2026-06-25", home: "Paraguay",  away: "Australia", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },

    // ── GROUP E ──────────────────────────────────────────────────
    { id: "E1", stage: "group", group: "E", matchday: 1, date: "2026-06-14", home: "Germany",     away: "Curaçao",     result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: "home", Grosi: "home", Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "E2", stage: "group", group: "E", matchday: 1, date: "2026-06-14", home: "Ivory Coast", away: "Ecuador",     result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: "draw", Grosi: "draw", Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "E3", stage: "group", group: "E", matchday: 2, date: "2026-06-20", home: "Germany",     away: "Ivory Coast", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "E4", stage: "group", group: "E", matchday: 2, date: "2026-06-20", home: "Ecuador",     away: "Curaçao",     result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "E5", stage: "group", group: "E", matchday: 3, date: "2026-06-25", home: "Curaçao",     away: "Ivory Coast", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "E6", stage: "group", group: "E", matchday: 3, date: "2026-06-25", home: "Ecuador",     away: "Germany",     result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },

    // ── GROUP F ──────────────────────────────────────────────────
    { id: "F1", stage: "group", group: "F", matchday: 1, date: "2026-06-14", home: "Netherlands", away: "Japan",   result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: "draw", Grosi: "draw", Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "F2", stage: "group", group: "F", matchday: 1, date: "2026-06-14", home: "Sweden",      away: "Tunisia", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: "home", Grosi: "home", Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "F3", stage: "group", group: "F", matchday: 2, date: "2026-06-20", home: "Netherlands", away: "Sweden",  result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "F4", stage: "group", group: "F", matchday: 2, date: "2026-06-20", home: "Tunisia",     away: "Japan",   result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "F5", stage: "group", group: "F", matchday: 3, date: "2026-06-25", home: "Japan",       away: "Sweden",  result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "F6", stage: "group", group: "F", matchday: 3, date: "2026-06-25", home: "Tunisia",     away: "Netherlands", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },

    // ── GROUP G ──────────────────────────────────────────────────
    { id: "G1", stage: "group", group: "G", matchday: 1, date: "2026-06-15", home: "Belgium",     away: "Egypt",       result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: "home", Grosi: "home", Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "G2", stage: "group", group: "G", matchday: 1, date: "2026-06-15", home: "Iran",        away: "New Zealand", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: "away", Grosi: "away", Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "G3", stage: "group", group: "G", matchday: 2, date: "2026-06-21", home: "Belgium",     away: "Iran",        result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "G4", stage: "group", group: "G", matchday: 2, date: "2026-06-21", home: "New Zealand", away: "Egypt",       result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "G5", stage: "group", group: "G", matchday: 3, date: "2026-06-26", home: "Belgium",     away: "New Zealand", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "G6", stage: "group", group: "G", matchday: 3, date: "2026-06-26", home: "Iran",        away: "Egypt",       result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },

    // ── GROUP H ──────────────────────────────────────────────────
    { id: "H1", stage: "group", group: "H", matchday: 1, date: "2026-06-15", home: "Spain",       away: "Cape Verde",  result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: "home", Grosi: "home", Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "H2", stage: "group", group: "H", matchday: 1, date: "2026-06-15", home: "Saudi Arabia", away: "Uruguay",    result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: "away", Grosi: "away", Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "H3", stage: "group", group: "H", matchday: 2, date: "2026-06-21", home: "Spain",       away: "Saudi Arabia", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "H4", stage: "group", group: "H", matchday: 2, date: "2026-06-21", home: "Uruguay",     away: "Cape Verde",  result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "H5", stage: "group", group: "H", matchday: 3, date: "2026-06-26", home: "Spain",       away: "Uruguay",     result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "H6", stage: "group", group: "H", matchday: 3, date: "2026-06-26", home: "Cape Verde",  away: "Saudi Arabia", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },

    // ── GROUP I ──────────────────────────────────────────────────
    { id: "I1", stage: "group", group: "I", matchday: 1, date: "2026-06-16", home: "France",  away: "Senegal", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: "home", Grosi: "home", Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "I2", stage: "group", group: "I", matchday: 1, date: "2026-06-16", home: "Iraq",    away: "Norway",  result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: "away", Grosi: "away", Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "I3", stage: "group", group: "I", matchday: 2, date: "2026-06-22", home: "Norway",  away: "Senegal", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "I4", stage: "group", group: "I", matchday: 2, date: "2026-06-22", home: "France",  away: "Iraq",    result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "I5", stage: "group", group: "I", matchday: 3, date: "2026-06-26", home: "France",  away: "Norway",  result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "I6", stage: "group", group: "I", matchday: 3, date: "2026-06-26", home: "Senegal", away: "Iraq",    result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },

    // ── GROUP J ──────────────────────────────────────────────────
    { id: "J1", stage: "group", group: "J", matchday: 1, date: "2026-06-16", home: "Argentina", away: "Algeria", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: "home", Grosi: "home", Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "J2", stage: "group", group: "J", matchday: 1, date: "2026-06-16", home: "Austria",   away: "Jordan",  result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: "home", Grosi: "home", Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "J3", stage: "group", group: "J", matchday: 2, date: "2026-06-22", home: "Argentina", away: "Austria", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "J4", stage: "group", group: "J", matchday: 2, date: "2026-06-22", home: "Jordan",    away: "Algeria", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "J5", stage: "group", group: "J", matchday: 3, date: "2026-06-27", home: "Jordan",    away: "Argentina", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "J6", stage: "group", group: "J", matchday: 3, date: "2026-06-27", home: "Algeria",   away: "Austria",   result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },

    // ── GROUP K ──────────────────────────────────────────────────
    { id: "K1", stage: "group", group: "K", matchday: 1, date: "2026-06-17", home: "Portugal",   away: "DR Congo",  result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: "home", Grosi: "home", Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "K2", stage: "group", group: "K", matchday: 1, date: "2026-06-17", home: "Uzbekistan", away: "Colombia",  result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: "away", Grosi: "away", Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "K3", stage: "group", group: "K", matchday: 2, date: "2026-06-23", home: "Portugal",   away: "Uzbekistan", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "K4", stage: "group", group: "K", matchday: 2, date: "2026-06-23", home: "Colombia",   away: "DR Congo",  result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "K5", stage: "group", group: "K", matchday: 3, date: "2026-06-27", home: "Colombia",   away: "Portugal",  result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "K6", stage: "group", group: "K", matchday: 3, date: "2026-06-27", home: "DR Congo",   away: "Uzbekistan", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },

    // ── GROUP L ──────────────────────────────────────────────────
    { id: "L1", stage: "group", group: "L", matchday: 1, date: "2026-06-17", home: "England", away: "Croatia", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: "draw", Grosi: "draw", Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "L2", stage: "group", group: "L", matchday: 1, date: "2026-06-17", home: "Ghana",   away: "Panama",  result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: "home", Grosi: "home", Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "L3", stage: "group", group: "L", matchday: 2, date: "2026-06-23", home: "England", away: "Ghana",   result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "L4", stage: "group", group: "L", matchday: 2, date: "2026-06-23", home: "Panama",  away: "Croatia", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "L5", stage: "group", group: "L", matchday: 3, date: "2026-06-27", home: "Panama",  away: "England", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "L6", stage: "group", group: "L", matchday: 3, date: "2026-06-27", home: "Croatia", away: "Ghana",   result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },

    // ── ROUND OF 32 (add teams once group stage is done) ─────────
    // No draw in knockout — "home" = win for listed home team, "away" = win for listed away team
    { id: "R32_1",  stage: "r32", group: null, matchday: null, date: "2026-06-28", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "R32_2",  stage: "r32", group: null, matchday: null, date: "2026-06-28", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "R32_3",  stage: "r32", group: null, matchday: null, date: "2026-06-29", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "R32_4",  stage: "r32", group: null, matchday: null, date: "2026-06-29", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "R32_5",  stage: "r32", group: null, matchday: null, date: "2026-06-30", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "R32_6",  stage: "r32", group: null, matchday: null, date: "2026-06-30", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "R32_7",  stage: "r32", group: null, matchday: null, date: "2026-07-01", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "R32_8",  stage: "r32", group: null, matchday: null, date: "2026-07-01", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "R32_9",  stage: "r32", group: null, matchday: null, date: "2026-07-02", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "R32_10", stage: "r32", group: null, matchday: null, date: "2026-07-02", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "R32_11", stage: "r32", group: null, matchday: null, date: "2026-07-03", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "R32_12", stage: "r32", group: null, matchday: null, date: "2026-07-03", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "R32_13", stage: "r32", group: null, matchday: null, date: "2026-07-04", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "R32_14", stage: "r32", group: null, matchday: null, date: "2026-07-04", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "R32_15", stage: "r32", group: null, matchday: null, date: "2026-07-05", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "R32_16", stage: "r32", group: null, matchday: null, date: "2026-07-05", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },

    // ── ROUND OF 16 ───────────────────────────────────────────────
    { id: "R16_1", stage: "r16", group: null, matchday: null, date: "2026-07-07", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "R16_2", stage: "r16", group: null, matchday: null, date: "2026-07-07", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "R16_3", stage: "r16", group: null, matchday: null, date: "2026-07-08", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "R16_4", stage: "r16", group: null, matchday: null, date: "2026-07-08", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "R16_5", stage: "r16", group: null, matchday: null, date: "2026-07-09", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "R16_6", stage: "r16", group: null, matchday: null, date: "2026-07-09", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "R16_7", stage: "r16", group: null, matchday: null, date: "2026-07-10", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "R16_8", stage: "r16", group: null, matchday: null, date: "2026-07-10", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },

    // ── QUARTER-FINALS ────────────────────────────────────────────
    { id: "QF1", stage: "qf", group: null, matchday: null, date: "2026-07-11", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "QF2", stage: "qf", group: null, matchday: null, date: "2026-07-11", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "QF3", stage: "qf", group: null, matchday: null, date: "2026-07-12", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "QF4", stage: "qf", group: null, matchday: null, date: "2026-07-12", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },

    // ── SEMI-FINALS ───────────────────────────────────────────────
    { id: "SF1", stage: "sf", group: null, matchday: null, date: "2026-07-14", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
    { id: "SF2", stage: "sf", group: null, matchday: null, date: "2026-07-15", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },

    // ── THIRD PLACE ───────────────────────────────────────────────
    { id: "3RD",  stage: "3rd", group: null, matchday: null, date: "2026-07-18", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },

    // ── FINAL ─────────────────────────────────────────────────────
    { id: "FINAL", stage: "final", group: null, matchday: null, date: "2026-07-19", home: "TBD", away: "TBD", result: null, tips: { Max: null, Mackenzie: null, Annette: null, Stefan: null, Xavier: null, Tony: null, Grosi: null, Debbie: null, Richard: null, Olivia: null, Sam: null } },
  ]
};
